import "../styles/globals.css";
import Navigation from "../components/Navigation";

const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
      </head>
      {/* Todo lo que se renderiza en nuestras rutas o componentes */}
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
